version: '3.5'

# 6300 auth
# 6301 - db_auth
# 6400 data
# 6401 - db_data

services:

  auth:
    restart: on-failure
    build: ./auth
    container_name: auth
    environment:
      - SECRET_KEY=SECRET_KEY
      - PORT=6300
      - DB_USERNAME=admin
      - DB_PASSWORD=Gaz12345!auth
      - DB_HOST=db_auth_museum
      - DB_PORT=6301
      - DB_NAME=postgres
      - TIME=100
    depends_on:
      - db_auth_museum
    networks:
      - internal_net
    volumes:
      - auth_vol:/app/migrations

  db_auth_museum:
    restart: on-failure
    container_name: db_auth_museum
    ports:
      - "6301:6301"
    environment:
      - POSTGRES_PASSWORD=Gaz12345!auth
      - POSTGRES_USER=admin
    image: postgres:14.3-alpine
    command:
      - "postgres"
      - "-c"
      - "port=6301"
    volumes:
      - db_auth_museum_vol:/var/lib/postgresql/data
    networks:
      - internal_net
  

  data:
    restart: on-failure
    build: ./data
    container_name: data
    environment:
      - SECRET_KEY=SECRET_KEY
      - PORT=6400
      - DB_USERNAME=admin
      - DB_PASSWORD=Gaz12345!data
      - DB_HOST=db_data_museum
      - DB_PORT=6401
      - DB_NAME=postgres
    depends_on:
      - db_data_museum
    networks:
      - internal_net
    volumes:
      - data_vol:/app/migrations

  db_data_museum:
    restart: on-failure
    container_name: db_data_museum
    ports:
      - "6401:6401"
    environment:
      - POSTGRES_PASSWORD=Gaz12345!data
      - POSTGRES_USER=admin
    image: postgres:14.3-alpine
    command:
      - "postgres"
      - "-c"
      - "port=6401"
    volumes:
      - db_data_museum_vol:/var/lib/postgresql/data
    networks:
      - internal_net
  
  nginx:
    restart: on-failure
    container_name: nginx
    image: nginx:1.23.1-alpine
    networks:
      - internal_net
    ports:
      - 80:80
    depends_on:
      - auth
      - data
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  frontend:
    restart: on-failure
    build: ./build  # Путь к Dockerfile для фронтенда
    container_name: frontend
    ports:
      - "6500:80"  # Открываем порт 6500 для сайта
    networks:
      - internal_net
    depends_on:
      - auth
      - data
    volumes:
      - ./build/web:/app  # Монтируем директорию с веб-файлами

volumes:
  db_auth_museum_vol: {}
  db_data_museum_vol: {}
  auth_vol: {}
  data_vol: {}

networks:
  internal_net:
    driver: bridge